/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
/**
 *
 * @author Julio
 */
public class Alimentos extends javax.swing.JFrame {

    /**
     * Creates new form AppMain
     */
    public Alimentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exercicios1 = new javax.swing.JButton();
        jLabe_AlimentosSugegidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        Exercicios2 = new javax.swing.JButton();
        BatataIMG = new javax.swing.JLabel();
        BatataTXT = new javax.swing.JLabel();
        FrangoIMG = new javax.swing.JLabel();
        FrangoTXT = new javax.swing.JLabel();
        ArrozIMG = new javax.swing.JLabel();
        ArrozTXT = new javax.swing.JLabel();
        BrocolisIMG = new javax.swing.JLabel();
        BrocolisTXT = new javax.swing.JLabel();
        TextoFinal = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        Exercicios1.setBackground(new java.awt.Color(0, 102, 102));
        Exercicios1.setForeground(new java.awt.Color(255, 255, 255));
        Exercicios1.setText("EXERCÍCIOS");
        Exercicios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exercicios1MouseClicked(evt);
            }
        });
        Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exercicios1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabe_AlimentosSugegidos.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabe_AlimentosSugegidos.setForeground(new java.awt.Color(0, 102, 102));
        jLabe_AlimentosSugegidos.setText("Alimentos Sugeridos");
        getContentPane().add(jLabe_AlimentosSugegidos);
        jLabe_AlimentosSugegidos.setBounds(60, 10, 210, 30);

        jLabel1.setText("Clique nos alimentos para mais detalhes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 40, 250, 50);

        jButtonVoltar.setBackground(new java.awt.Color(0, 204, 204));
        jButtonVoltar.setForeground(new java.awt.Color(0, 102, 102));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/seta.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(10, 10, 20, 30);

        Exercicios2.setBackground(new java.awt.Color(0, 102, 102));
        Exercicios2.setForeground(new java.awt.Color(255, 255, 255));
        Exercicios2.setText("VER EXERCÍCIOS");
        Exercicios2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exercicios2MouseClicked(evt);
            }
        });
        Exercicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exercicios2ActionPerformed(evt);
            }
        });
        getContentPane().add(Exercicios2);
        Exercicios2.setBounds(70, 470, 170, 60);

        BatataIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/batata.png"))); // NOI18N
        BatataIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatataIMGMouseClicked(evt);
            }
        });
        getContentPane().add(BatataIMG);
        BatataIMG.setBounds(30, 100, 120, 80);

        BatataTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        BatataTXT.setForeground(new java.awt.Color(0, 102, 102));
        BatataTXT.setText("Batata Doce");
        getContentPane().add(BatataTXT);
        BatataTXT.setBounds(50, 180, 90, 17);

        FrangoIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frango.png"))); // NOI18N
        FrangoIMG.setText("jLabel13");
        FrangoIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrangoIMGMouseClicked(evt);
            }
        });
        getContentPane().add(FrangoIMG);
        FrangoIMG.setBounds(180, 100, 120, 80);

        FrangoTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        FrangoTXT.setForeground(new java.awt.Color(0, 102, 102));
        FrangoTXT.setText("Frango Grelhado");
        getContentPane().add(FrangoTXT);
        FrangoTXT.setBounds(190, 180, 110, 20);

        ArrozIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Arroz.png"))); // NOI18N
        ArrozIMG.setText("jLabel10");
        ArrozIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArrozIMGMouseClicked(evt);
            }
        });
        getContentPane().add(ArrozIMG);
        ArrozIMG.setBounds(30, 220, 120, 80);

        ArrozTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        ArrozTXT.setForeground(new java.awt.Color(0, 102, 102));
        ArrozTXT.setText("Arroz Integral");
        getContentPane().add(ArrozTXT);
        ArrozTXT.setBounds(50, 300, 110, 17);

        BrocolisIMG.setForeground(new java.awt.Color(44, 51, 58));
        BrocolisIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brocolis.png"))); // NOI18N
        BrocolisIMG.setText("jLabel11");
        BrocolisIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrocolisIMGMouseClicked(evt);
            }
        });
        getContentPane().add(BrocolisIMG);
        BrocolisIMG.setBounds(180, 220, 120, 80);

        BrocolisTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        BrocolisTXT.setForeground(new java.awt.Color(0, 102, 102));
        BrocolisTXT.setText("Brócolis");
        getContentPane().add(BrocolisTXT);
        BrocolisTXT.setBounds(210, 300, 60, 17);

        TextoFinal.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        TextoFinal.setForeground(new java.awt.Color(0, 102, 102));
        TextoFinal.setText("<html> É importante que a pessoa<br> mantenha uma alimentação<br> saudável junto com a prática<br> de exercícios físicos.<br>");
        TextoFinal.setToolTipText("");
        getContentPane().add(TextoFinal);
        TextoFinal.setBounds(50, 350, 240, 90);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teladeFndo1.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 320, 570);

        setSize(new java.awt.Dimension(336, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BatataIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatataIMGMouseClicked
        DescricaoBatata descBatata = new DescricaoBatata();
        descBatata.setVisible(true);
    }//GEN-LAST:event_BatataIMGMouseClicked

    private void FrangoIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrangoIMGMouseClicked
        DescricaoFrango descFrango = new DescricaoFrango();
        descFrango.setVisible(true);
    }//GEN-LAST:event_FrangoIMGMouseClicked

    private void ArrozIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrozIMGMouseClicked
        DescricaoArroz descArroz = new DescricaoArroz();
        descArroz.setVisible(true);
    }//GEN-LAST:event_ArrozIMGMouseClicked

    private void BrocolisIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrocolisIMGMouseClicked
        DescricaoBroc descBroc = new DescricaoBroc();
        descBroc.setVisible(true);
    }//GEN-LAST:event_BrocolisIMGMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        IMC back = new IMC();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void Exercicios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exercicios1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Exercicios1MouseClicked

    private void Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exercicios1ActionPerformed
        
    }//GEN-LAST:event_Exercicios1ActionPerformed

    private void Exercicios2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exercicios2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Exercicios2MouseClicked

    private void Exercicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exercicios2ActionPerformed
        Exercicios telaExc = new Exercicios();
        telaExc.setVisible(true);
        dispose();
    }//GEN-LAST:event_Exercicios2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArrozIMG;
    private javax.swing.JLabel ArrozTXT;
    private javax.swing.JLabel BatataIMG;
    private javax.swing.JLabel BatataTXT;
    private javax.swing.JLabel BrocolisIMG;
    private javax.swing.JLabel BrocolisTXT;
    private javax.swing.JButton Exercicios1;
    private javax.swing.JButton Exercicios2;
    private javax.swing.JLabel FrangoIMG;
    private javax.swing.JLabel FrangoTXT;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel TextoFinal;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabe_AlimentosSugegidos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
