/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Julio
 */
public class DescricaoAbdominal extends javax.swing.JFrame {

    /**
     * Creates new form Descricao
     */
    public DescricaoAbdominal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        ExcTXT = new javax.swing.JLabel();
        ExecucaoTXT = new javax.swing.JLabel();
        Execucao = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Texto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Texto.setText("<html>\n<pre>\nO objetivo do exercício é \ncontrair e relaxar o abdômen,\nmexendo com os músculos\nda área, inclusive os  \nintercostais e o diafragma.\n\nOs exercícios abdominais \najudam a fortalecer o abdômen\ne proporcionam mais equilíbrio\nao tronco, econtribui para uma\nmelhor postura.\n</pre>");
        Texto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextoPropertyChange(evt);
            }
        });
        getContentPane().add(Texto);
        Texto.setBounds(40, 60, 210, 200);

        ExcTXT.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ExcTXT.setText("Abdominal");
        getContentPane().add(ExcTXT);
        ExcTXT.setBounds(90, 20, 120, 25);

        ExecucaoTXT.setText("<html>\n Faça 2 seções entre 15 a 20 repetições<br>\ncom intervalo de 30 segundos ou 1<br>\nminuto cada. Realize o exercício de<br>\nforma controlada tendo intuíto de<br>\ntrabalhar melhor o musculo abdominal.");
        getContentPane().add(ExecucaoTXT);
        ExecucaoTXT.setBounds(40, 310, 220, 100);

        Execucao.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Execucao.setText("Execução");
        getContentPane().add(Execucao);
        Execucao.setBounds(90, 280, 110, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teladeFndo1.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 280, 430);

        setSize(new java.awt.Dimension(297, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescricaoAbdominal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescricaoAbdominal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescricaoAbdominal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescricaoAbdominal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescricaoAbdominal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExcTXT;
    private javax.swing.JLabel Execucao;
    private javax.swing.JLabel ExecucaoTXT;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
