/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Julio
 */
public class Exercicios extends javax.swing.JFrame {

    /**
     * Creates new form AppMain
     */
    public Exercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExerciciosSugegidos = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        Alimentos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FlexaoIMG = new javax.swing.JLabel();
        FlexaoTXT = new javax.swing.JLabel();
        AbdominalIMG = new javax.swing.JLabel();
        AbdominalTXT = new javax.swing.JLabel();
        AgachamentoIMG = new javax.swing.JLabel();
        AgachamentoTXT = new javax.swing.JLabel();
        PularCordaIMG = new javax.swing.JLabel();
        PularCordaTXT = new javax.swing.JLabel();
        TextoFinal = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ExerciciosSugegidos.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ExerciciosSugegidos.setForeground(new java.awt.Color(0, 102, 102));
        ExerciciosSugegidos.setText("Exercícios Recomendados");
        getContentPane().add(ExerciciosSugegidos);
        ExerciciosSugegidos.setBounds(40, 20, 280, 30);

        jButtonVoltar.setBackground(new java.awt.Color(0, 204, 204));
        jButtonVoltar.setForeground(new java.awt.Color(0, 102, 102));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/seta.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(10, 10, 20, 30);

        Alimentos.setBackground(new java.awt.Color(0, 102, 102));
        Alimentos.setForeground(new java.awt.Color(255, 255, 255));
        Alimentos.setText("VER ALIMENTOS");
        Alimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlimentosMouseClicked(evt);
            }
        });
        Alimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentosActionPerformed(evt);
            }
        });
        getContentPane().add(Alimentos);
        Alimentos.setBounds(70, 470, 170, 60);

        jLabel1.setText("Clique nos exercícios para mais detalhes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 50, 250, 40);

        FlexaoIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Flexão.png"))); // NOI18N
        FlexaoIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlexaoIMGMouseClicked(evt);
            }
        });
        getContentPane().add(FlexaoIMG);
        FlexaoIMG.setBounds(30, 100, 120, 80);

        FlexaoTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        FlexaoTXT.setForeground(new java.awt.Color(0, 102, 102));
        FlexaoTXT.setText("Flexão");
        getContentPane().add(FlexaoTXT);
        FlexaoTXT.setBounds(70, 180, 60, 17);

        AbdominalIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Abdominal.png"))); // NOI18N
        AbdominalIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbdominalIMGMouseClicked(evt);
            }
        });
        getContentPane().add(AbdominalIMG);
        AbdominalIMG.setBounds(180, 100, 120, 80);

        AbdominalTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        AbdominalTXT.setForeground(new java.awt.Color(0, 102, 102));
        AbdominalTXT.setText("Abdominal");
        getContentPane().add(AbdominalTXT);
        AbdominalTXT.setBounds(210, 180, 70, 20);

        AgachamentoIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agachamento.png"))); // NOI18N
        AgachamentoIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgachamentoIMGMouseClicked(evt);
            }
        });
        getContentPane().add(AgachamentoIMG);
        AgachamentoIMG.setBounds(30, 220, 120, 90);

        AgachamentoTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        AgachamentoTXT.setForeground(new java.awt.Color(0, 102, 102));
        AgachamentoTXT.setText("Agachamento");
        getContentPane().add(AgachamentoTXT);
        AgachamentoTXT.setBounds(50, 310, 90, 17);

        PularCordaIMG.setForeground(new java.awt.Color(44, 51, 58));
        PularCordaIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PularCorda.png"))); // NOI18N
        PularCordaIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PularCordaIMGMouseClicked(evt);
            }
        });
        getContentPane().add(PularCordaIMG);
        PularCordaIMG.setBounds(180, 220, 120, 90);

        PularCordaTXT.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        PularCordaTXT.setForeground(new java.awt.Color(0, 102, 102));
        PularCordaTXT.setText("Pular Corda");
        getContentPane().add(PularCordaTXT);
        PularCordaTXT.setBounds(200, 310, 90, 17);

        TextoFinal.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        TextoFinal.setForeground(new java.awt.Color(0, 102, 102));
        TextoFinal.setText("<html> Os exercícios físicos são de<br> suma importância para auxiliar <br>  no metabolismo e na saúde<br>  tanto física quando mental.<br>      ");
        TextoFinal.setToolTipText("");
        getContentPane().add(TextoFinal);
        TextoFinal.setBounds(40, 340, 250, 110);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teladeFndo1.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 320, 570);

        setSize(new java.awt.Dimension(336, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FlexaoIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlexaoIMGMouseClicked
       DescricaoFlexao descExc = new DescricaoFlexao();
       descExc.setVisible(true);
    }//GEN-LAST:event_FlexaoIMGMouseClicked

    private void AbdominalIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbdominalIMGMouseClicked
       DescricaoAbdominal descExc = new DescricaoAbdominal();
       descExc.setVisible(true);
    }//GEN-LAST:event_AbdominalIMGMouseClicked

    private void AgachamentoIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgachamentoIMGMouseClicked

       DescricaoAgachamento descExc = new DescricaoAgachamento();
       descExc.setVisible(true);
    }//GEN-LAST:event_AgachamentoIMGMouseClicked

    private void PularCordaIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PularCordaIMGMouseClicked
       DescricaoPularCorda descExc = new DescricaoPularCorda();
       descExc.setVisible(true);
    }//GEN-LAST:event_PularCordaIMGMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        IMC back = new IMC();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void AlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlimentosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AlimentosMouseClicked

    private void AlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentosActionPerformed
        Alimentos telaAli = new Alimentos();
        telaAli.setVisible(true);
        dispose();
    }//GEN-LAST:event_AlimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbdominalIMG;
    private javax.swing.JLabel AbdominalTXT;
    private javax.swing.JLabel AgachamentoIMG;
    private javax.swing.JLabel AgachamentoTXT;
    private javax.swing.JButton Alimentos;
    private javax.swing.JLabel ExerciciosSugegidos;
    private javax.swing.JLabel FlexaoIMG;
    private javax.swing.JLabel FlexaoTXT;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel PularCordaIMG;
    private javax.swing.JLabel PularCordaTXT;
    private javax.swing.JLabel TextoFinal;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
