/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Login.login;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form AppMain
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEntrar = new javax.swing.JButton();
        TitleIMC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PesoTXT = new javax.swing.JFormattedTextField();
        AlturaTXT = new javax.swing.JFormattedTextField();
        Peso = new javax.swing.JLabel();
        Peso1 = new javax.swing.JLabel();
        TitleIMC1 = new javax.swing.JLabel();
        Alimentos = new javax.swing.JButton();
        TotalIMC = new javax.swing.JTextField();
        CalcularBTN1 = new javax.swing.JButton();
        Exercicios1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Limpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        jButtonEntrar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TitleIMC.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        TitleIMC.setText("Seu IMC:");
        getContentPane().add(TitleIMC);
        TitleIMC.setBounds(30, 220, 150, 50);

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 530, 80, 20);

        PesoTXT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##,#0"))));
        PesoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoTXTActionPerformed(evt);
            }
        });
        getContentPane().add(PesoTXT);
        PesoTXT.setBounds(30, 90, 140, 40);

        AlturaTXT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##"))));
        getContentPane().add(AlturaTXT);
        AlturaTXT.setBounds(30, 180, 140, 40);

        Peso.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Peso.setText("Informe Sua Altura:");
        getContentPane().add(Peso);
        Peso.setBounds(30, 140, 180, 20);

        Peso1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Peso1.setText("Informe Seu Peso:");
        getContentPane().add(Peso1);
        Peso1.setBounds(30, 50, 150, 20);

        TitleIMC1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        TitleIMC1.setText("Calculadora IMC");
        getContentPane().add(TitleIMC1);
        TitleIMC1.setBounds(130, 10, 260, 40);

        Alimentos.setBackground(new java.awt.Color(0, 102, 102));
        Alimentos.setForeground(new java.awt.Color(255, 255, 255));
        Alimentos.setText("ALIMENTOS");
        Alimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlimentosMouseClicked(evt);
            }
        });
        Alimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentosActionPerformed(evt);
            }
        });
        getContentPane().add(Alimentos);
        Alimentos.setBounds(180, 440, 120, 60);

        TotalIMC.setEditable(false);
        getContentPane().add(TotalIMC);
        TotalIMC.setBounds(30, 260, 90, 50);

        CalcularBTN1.setBackground(new java.awt.Color(0, 102, 102));
        CalcularBTN1.setForeground(new java.awt.Color(255, 255, 255));
        CalcularBTN1.setText("Calcular");
        CalcularBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcularBTN1MouseClicked(evt);
            }
        });
        CalcularBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularBTN1ActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularBTN1);
        CalcularBTN1.setBounds(200, 180, 100, 40);

        Exercicios1.setBackground(new java.awt.Color(0, 102, 102));
        Exercicios1.setForeground(new java.awt.Color(255, 255, 255));
        Exercicios1.setText("EXERCÍCIOS");
        Exercicios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exercicios1MouseClicked(evt);
            }
        });
        Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exercicios1ActionPerformed(evt);
            }
        });
        getContentPane().add(Exercicios1);
        Exercicios1.setBounds(20, 440, 120, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("<html>\n<pre>\nApós calcular o IMC, você pode verificar\na página de Exercícios Sugeridos, \nou Alimentos Sugeridos para o seu IMC.\n</pre>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 330, 290, 80);

        Limpar.setBackground(new java.awt.Color(0, 102, 102));
        Limpar.setForeground(new java.awt.Color(255, 255, 255));
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar);
        Limpar.setBounds(150, 270, 100, 30);

        jLabel2.setText("Apenas Números");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 100, 14);

        jLabel3.setText("Apenas Números");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 100, 14);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teladeFndo1.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 320, 570);

        setSize(new java.awt.Dimension(336, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed

    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void AlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentosActionPerformed
       String imc;
       StringBuilder mensagem = new StringBuilder();
        
        imc = TotalIMC.getText();
        
        if (imc.equals("")) {
           mensagem.append("Você deve realizar o cálculo de IMC!");
           JOptionPane.showMessageDialog(null, mensagem);
        } else if (!"".equals(imc)){
            Alimentos telaAli = new Alimentos();
            telaAli.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_AlimentosActionPerformed

    private void AlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlimentosMouseClicked
        
    }//GEN-LAST:event_AlimentosMouseClicked

    private void CalcularBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularBTN1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularBTN1MouseClicked

    private void CalcularBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularBTN1ActionPerformed
       double peso, altura, total;
       String validarPeso;
       String validarAltura;
       StringBuilder mensagem = new StringBuilder();
       DecimalFormat df = new DecimalFormat("##.##");
       
       validarPeso = PesoTXT.getText();
       validarAltura = AlturaTXT.getText();
       
        if (validarPeso.equals("") && validarAltura.equals("")) {
           mensagem.append("Você deve informar o PESO e a ALTURA!");
           JOptionPane.showMessageDialog(null, mensagem);
        } else 
           if (validarAltura.equals("")){
           mensagem.append("Você deve informar a ALTURA!");
           JOptionPane.showMessageDialog(null, mensagem);
        } else 
           if (validarPeso.equals("")) {
           mensagem.append("Você deve informar o PESO!");
           JOptionPane.showMessageDialog(null, mensagem);
        }
       
        peso = Double.parseDouble(PesoTXT.getText());
        altura = Double.parseDouble(AlturaTXT.getText());
       
        if(!"".equals(validarPeso) && !"".equals(validarAltura)){
            total  = peso / (altura*altura);
            TotalIMC.setText(String.valueOf(df.format(total)));
        }
    }//GEN-LAST:event_CalcularBTN1ActionPerformed

    private void Exercicios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exercicios1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Exercicios1MouseClicked

    private void Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exercicios1ActionPerformed
        String imc;
        StringBuilder mensagem = new StringBuilder();
        Exercicios telaExc = new Exercicios();
        
        imc = TotalIMC.getText();
        
        if (imc.equals("")) {
           mensagem.append("O campo de IMC deve estar preenchido após o cálculo!");
           JOptionPane.showMessageDialog(null, mensagem);
        } else if (!"".equals(imc)) {
            telaExc.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Exercicios1ActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        PesoTXT.setText("");
        AlturaTXT.setText("");
        TotalIMC.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void PesoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoTXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login voltar = new login();
        voltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alimentos;
    private javax.swing.JFormattedTextField AlturaTXT;
    private javax.swing.JButton CalcularBTN1;
    private javax.swing.JButton Exercicios1;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton Limpar;
    private javax.swing.JLabel Peso;
    private javax.swing.JLabel Peso1;
    private javax.swing.JFormattedTextField PesoTXT;
    private javax.swing.JLabel TitleIMC;
    private javax.swing.JLabel TitleIMC1;
    private javax.swing.JTextField TotalIMC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
